In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AIML/Dataset/Data.csv')
dataset = data
independent = dataset.iloc[:,:-1].values
print(independent)
dependent = dataset.iloc[:,-1].values
print(dependent)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
independent[:,1:3] = imputer.fit_transform(independent[:,1:3])
independent

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

le = LabelEncoder()
independent[:,0] = le.fit_transform(independent[:,0])
independent

array([[0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([('apple',OneHotEncoder(),[0])],remainder="passthrough")
independent = ct.fit_transform(independent)
independent.astype(int)

array([[    0,     1,     0,     0,    44, 72000],
       [    1,     0,     0,     1,    27, 48000],
       [    1,     0,     1,     0,    30, 54000],
       [    1,     0,     0,     1,    38, 61000],
       [    1,     0,     1,     0,    40, 63777],
       [    0,     1,     0,     0,    35, 58000],
       [    1,     0,     0,     1,    38, 52000],
       [    0,     1,     0,     0,    48, 79000],
       [    1,     0,     1,     0,    50, 83000],
       [    0,     1,     0,     0,    37, 67000]])

In [ ]:
dependent = le.fit_transform(dependent)
dependent

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
train_test_split(independent,dependent,test_size=0.2, random_state=45)

In [ ]:
X_train

array([[0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0]], dtype=object)

In [ ]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2)
