In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
plt.style.use('dark_background')
data = pd.read_csv('../Dataset/bestsellers.csv')
data

**Using Tree**

In [220]:
print(len(data))
data = data.drop_duplicates(subset=['Name','Author'])
print(len(data))

550
351


In [221]:
X = data.iloc[:,2:-1]
y = data.iloc[:,-1]

In [222]:
si = SimpleImputer(missing_values=np.nan ,strategy='mean')
X = si.fit_transform(X)
sc = StandardScaler()
X = sc.fit_transform(X)
le = LabelEncoder()
y = le.fit_transform(y)

In [223]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=1)


---
**this is whihout considering author**

In [224]:
tree = DecisionTreeClassifier(criterion='entropy',random_state=0)
tree.fit(X_train,y_train)
y_pred = tree.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_test,y_pred))


[[21 16]
 [18 33]]
              precision    recall  f1-score   support

           0       0.57      0.54      0.55        39
           1       0.65      0.67      0.66        49

    accuracy                           0.61        88
   macro avg       0.61      0.61      0.61        88
weighted avg       0.61      0.61      0.61        88



---
**this is with author**

In [225]:
X = data.iloc[:,1:-1]
y = data.iloc[:,-1]
le = LabelEncoder()
X.iloc[:,0] = le.fit_transform(X.iloc[:,0])

In [226]:
si = SimpleImputer(missing_values=np.nan ,strategy='mean')
X.iloc[:,1:] = si.fit_transform(X.iloc[:,1:])
sc = StandardScaler()
X = sc.fit_transform(X)
le = LabelEncoder()
y = le.fit_transform(y)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=1)

In [227]:
tree = DecisionTreeClassifier(criterion='entropy',random_state=0)
tree.fit(X_train,y_train)
y_pred = tree.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_test,y_pred))

[[22 15]
 [17 34]]
              precision    recall  f1-score   support

           0       0.59      0.56      0.58        39
           1       0.67      0.69      0.68        49

    accuracy                           0.64        88
   macro avg       0.63      0.63      0.63        88
weighted avg       0.63      0.64      0.64        88



**Logistic Regression**

In [228]:
from sklearn.linear_model import LogisticRegression

In [229]:
regression = LogisticRegression(random_state=1)
regression.fit(X_train,y_train)
y_pred = regression.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[14 25]
 [ 7 42]]
              precision    recall  f1-score   support

           0       0.67      0.36      0.47        39
           1       0.63      0.86      0.72        49

    accuracy                           0.64        88
   macro avg       0.65      0.61      0.60        88
weighted avg       0.64      0.64      0.61        88

